FROM nginx:1.25-alpine

# Copier la configuration nginx
COPY _docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Copier les fichiers publics Symfony (builds, index.php, assets…)
COPY --from=ferme-back-php-image:prod /var/www/html/public /var/www/html
