framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        cookie_domain: '.rfess.fr'

    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers:
        X-Forwarded-Proto: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
